name: knobkraft-orm
base: core20 # the base snap is the execution environment for this snap
version: git
summary: Free MIDI Sysex Librarian with extensive synth device support
description: |
  Free MIDI Sysex Librarian with extensive synth device support

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic

apps:
  knobkraft-orm:
    command: usr/local/bin/KnobKraftOrm

parts:
  knobkraft-orm:
    # See 'snapcraft plugins'
    plugin: cmake
    source: .
    source-type: git
    cmake-parameters:
      - -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=off -DPYTHON_EXECUTABLE=/usr/bin/python3.8 -DPYTHON_VERSION_TO_EMBED=3.8 -DSENTRY_CRASH_REPORTING=ON -DSENTRY_DSN=$SENTRY_DSN
#    override-build: |
#      snapcraftctl build
    build-packages:
      - pkg-config
      - libcurl4-openssl-dev
      - libasound2-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libglew-dev
      - libjack-dev
      - libncurses5-dev
      - libsecret-1-dev
      - libboost-dev
      - libicu-dev
      - libpython3-dev
      - python3
      - python3-pip
      - git
    stage-packages:
      - libasn1-8-heimdal
      - libasound2
      - libbrotli1
      - libcurl4
      - libfreetype6
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpng16-16
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsecret-1-0
      - libssh-4
      - libwind0-heimdal
